#define PARAM_CONST_LEVEL 0

#define PARAM_LINE_FROM_VALUE 0
#define PARAM_LINE_TO_VALUE 1

#define PARAM_QUADRATIC_P0 0
#define PARAM_QUADRATIC_P1 1
#define PARAM_QUADRATIC_P2 2

#define PARAM_CUBIC_P0 0
#define PARAM_CUBIC_P1 1
#define PARAM_CUBIC_P2 2
#define PARAM_CUBIC_P3 3

#define PARAM_SIN_FROM 0
#define PARAM_SIN_TO 1
#define PARAM_SIN_PERIOD 2
#define PARAM_SIN_PHASE 3
